sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1347azhz
  alioss:


  redis:
    host: localhost
    port: 6379
    password: 1347azhz
    database: 10


